blank_issues_enabled: false
contact_links:
  - name: Questions/discussion
    url: https://github.com/midnight-security/alarmo/discussions
    about: Ask questions, discuss configuration, share your setup